Document: rtpflood
Title: Debian rtpflood Manual
Author: <insert document author here>
Abstract: This manual describes what rtpflood is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/rtpflood/rtpflood.sgml.gz

Format: postscript
Files: /usr/share/doc/rtpflood/rtpflood.ps.gz

Format: text
Files: /usr/share/doc/rtpflood/rtpflood.text.gz

Format: HTML
Index: /usr/share/doc/rtpflood/html/index.html
Files: /usr/share/doc/rtpflood/html/*.html
